// Presets de fábrica. Los valores son "reales" (Hz, s, %, nombres de enum);
// main.js los convierte a normalizados. fx: lista de hasta 4 slots.
export const PRESETS = [
  {
    name: 'Init', category: 'Template', description: 'Punto de partida: sierra analógica y filtro LP.',
    macroNames: ['Cutoff', 'Space', 'Motion', 'Drive'],
    params: { 'a.type': 'Analog', 'b.on': 'Off', 'f1.cutoff': 8000, 'f1.res': 0.15 },
    fx: [], mods: [['macro1', 'f1.cutoff', 0.5]],
  },
  {
    name: 'Prisma Pad', category: 'Pad', description: 'Wavetable vocal en A y sierra unison en B, lento y ancho. Macro 1 abre el filtro, Macro 3 mueve la tabla.',
    macroNames: ['Open', 'Space', 'Motion', 'Shimmer'],
    params: {
      'a.type': 'Wavetable', 'a.wt.table': 'Vox', 'a.wt.pos': 0.3, 'a.wt.unison': 3, 'a.wt.detune': 18, 'a.wt.spread': 0.8, 'a.level': 0.7,
      'b.on': 'On', 'b.type': 'Analog', 'b.va.wave': 'Saw', 'b.va.unison': 5, 'b.va.detune': 22, 'b.va.spread': 0.9, 'b.level': 0.45, 'b.octave': -1, 'b.filter': 'F1',
      'f1.type': 'LP24', 'f1.cutoff': 1200, 'f1.res': 0.25, 'f1.keytrack': 0.3,
      'env1.attack': 0.8, 'env1.decay': 1, 'env1.sustain': 0.85, 'env1.release': 1.8,
      'env2.attack': 1.5, 'env2.decay': 2, 'env2.sustain': 0.6, 'env2.release': 2,
      'lfo1.rate': 0.12, 'lfo1.shape': 'Sine', 'lfo2.rate': 0.07, 'lfo2.shape': 'Triangle', 'master.volume': 0.7,
    },
    fx: [{ type: 'Chorus', mix: 0.5, params: [0.4, 0.6, 14, 0.1, 0.8, '3'] }, { type: 'Reverb', mix: 0.45, params: [0.85, 0.35, 30, 1, 150, 0.15] }],
    mods: [['env2', 'f1.cutoff', 0.35], ['macro1', 'f1.cutoff', 0.5], ['lfo1', 'a.wt.pos', 0.25], ['macro3', 'a.wt.pos', 0.5], ['lfo2', 'b.fine', 0.04], ['macro2', 'fx2.mix', 0.5], ['macro4', 'fx2.p5', 0.8]],
  },
  {
    name: 'Glass Keys', category: 'Keys', description: 'FM de 3 operadores con índice controlado por Env 3. Delay y reverb suaves.',
    macroNames: ['Brightness', 'Echo', 'Detune', 'Space'],
    params: {
      'a.type': 'FM', 'a.fm.alg': '3›2›1', 'a.fm.ratio2': 3.5, 'a.fm.index2': 1.2, 'a.fm.ratio3': 1, 'a.fm.index3': 2, 'a.level': 0.75,
      'b.on': 'On', 'b.type': 'Analog', 'b.va.wave': 'Sine', 'b.level': 0.3, 'b.octave': 1, 'b.filter': 'F1',
      'f1.cutoff': 12000, 'env1.attack': 0.003, 'env1.decay': 1.5, 'env1.sustain': 0.25, 'env1.release': 1.2,
      'env3.attack': 0.002, 'env3.decay': 0.6, 'env3.sustain': 0.1, 'env3.release': 0.5,
    },
    fx: [{ type: 'Delay', mix: 0.3, params: [375, 0.4, 4000, 0.7, '1/8D', 150] }, { type: 'Reverb', mix: 0.3, params: [0.6, 0.5, 15, 0.9, 200, 0] }],
    mods: [['env3', 'a.fm.index2', 0.25], ['velocity', 'a.fm.index2', 0.15], ['macro1', 'a.fm.index2', 0.4], ['macro2', 'fx1.mix', 0.6], ['macro3', 'b.fine', 0.1], ['macro4', 'fx2.mix', 0.6]],
  },
  {
    name: 'Granular Choir', category: 'Texture', description: 'Nubes de granos sobre un coro interno, formante en B. LFO barre la posición.',
    macroNames: ['Position', 'Spray', 'Size', 'Space'],
    params: {
      'a.type': 'Granular', 'a.gran.source': 'Choir', 'a.gran.size': 140, 'a.gran.density': 30, 'a.gran.pos': 0.3, 'a.gran.spray': 0.25, 'a.gran.shape': 0.8, 'a.gran.pitchRnd': 0.1, 'a.level': 0.8,
      'b.on': 'On', 'b.type': 'Wavetable', 'b.wt.table': 'Formant', 'b.wt.pos': 0.5, 'b.wt.unison': 2, 'b.level': 0.3, 'b.filter': 'F2',
      'f1.cutoff': 9000, 'f2.type': 'LP12', 'f2.cutoff': 2500,
      'env1.attack': 0.6, 'env1.decay': 1, 'env1.sustain': 1, 'env1.release': 2.5,
      'lfo1.rate': 0.05, 'lfo1.shape': 'Triangle', 'lfo1.retrig': 'Free', 'lfo2.rate': 0.3, 'lfo2.shape': 'Drift',
    },
    fx: [{ type: 'Chorus', mix: 0.4, params: [0.3, 0.5, 18, 0.1, 1, '2'] }, { type: 'Reverb', mix: 0.55, params: [0.92, 0.3, 40, 1, 120, 0.25] }],
    mods: [['lfo1', 'a.gran.pos', 0.3], ['macro1', 'a.gran.pos', 0.6], ['macro2', 'a.gran.spray', 0.7], ['macro3', 'a.gran.size', 0.5], ['macro4', 'fx2.mix', 0.4], ['lfo2', 'b.wt.pos', 0.3]],
  },
  {
    name: 'Modal Bells', category: 'Keys', description: 'Resonadores modales (material campana) más parciales armónicos. Reverb con shimmer.',
    macroNames: ['Material', 'Decay', 'Shimmer', 'Brightness'],
    params: {
      'a.type': 'Modal', 'a.modal.material': 0.9, 'a.modal.modes': 12, 'a.modal.decay': 3.5, 'a.modal.damp': 0.45, 'a.modal.pos': 0.22, 'a.modal.exciter': 'Click', 'a.modal.bright': 0.8, 'a.level': 0.7,
      'b.on': 'On', 'b.type': 'Harmonic', 'b.harm.partials': 6, 'b.harm.tilt': 1.6, 'b.harm.stretch': 0.3, 'b.level': 0.25, 'b.octave': 1, 'b.filter': 'F1',
      'f1.cutoff': 14000, 'env1.attack': 0.002, 'env1.decay': 2.5, 'env1.sustain': 0.4, 'env1.release': 2,
    },
    fx: [{ type: 'Delay', mix: 0.25, params: [500, 0.35, 3000, 0.8, '1/4D', 200] }, { type: 'Reverb', mix: 0.5, params: [0.9, 0.3, 20, 1, 150, 0.5] }],
    mods: [['macro1', 'a.modal.material', -0.5], ['macro2', 'a.modal.decay', 0.4], ['macro3', 'fx2.p5', 0.5], ['macro4', 'a.modal.bright', 0.3], ['velocity', 'a.modal.bright', 0.3]],
  },
  {
    name: 'Acid Bass', category: 'Bass', description: 'Mono legato con glide, LP24 resonante barrido por Env 2 y distorsión.',
    macroNames: ['Cutoff', 'Reso', 'Drive', 'Env Amt'],
    params: {
      'a.type': 'Analog', 'a.va.wave': 'Saw', 'a.level': 0.9, 'b.on': 'Off',
      'master.poly': 'Legato', 'master.glide': 0.12,
      'f1.type': 'LP24', 'f1.cutoff': 300, 'f1.res': 0.75, 'f1.drive': 0.3,
      'env1.attack': 0.002, 'env1.decay': 0.3, 'env1.sustain': 0.7, 'env1.release': 0.1,
      'env2.attack': 0.002, 'env2.decay': 0.25, 'env2.sustain': 0.05, 'env2.release': 0.1,
    },
    fx: [{ type: 'Distortion', mix: 0.6, params: [0.35, 'Soft', 6000, 0.1, 40, 0.7] }, { type: 'Delay', mix: 0.15, params: [375, 0.3, 3000, 1, '1/8', 200] }],
    mods: [['env2', 'f1.cutoff', 0.45], ['macro1', 'f1.cutoff', 0.5], ['macro2', 'f1.res', 0.3], ['macro3', 'fx1.p0', 0.6], ['macro4', 'env2.sustain', 0.8], ['modwheel', 'f1.cutoff', 0.3]],
  },
  {
    name: 'Corroded Lead', category: 'Lead', description: 'Wavetable Digital con unison, atravesada por el Corroder (FM + grano) y delay sincronizado.',
    macroNames: ['Corrode', 'Grain', 'Warp', 'Echo'],
    params: {
      'a.type': 'Wavetable', 'a.wt.table': 'Digital', 'a.wt.pos': 0.4, 'a.wt.warp': 0.2, 'a.wt.warpMode': 'Bend', 'a.wt.unison': 3, 'a.wt.detune': 10, 'a.level': 0.8,
      'b.on': 'On', 'b.type': 'Analog', 'b.va.wave': 'Pulse', 'b.va.pw': 0.3, 'b.octave': -1, 'b.level': 0.35, 'b.filter': 'F1',
      'f1.type': 'LP12', 'f1.cutoff': 4000, 'f1.res': 0.3, 'master.poly': 'Mono', 'master.glide': 0.05,
      'env1.attack': 0.01, 'env1.decay': 0.4, 'env1.sustain': 0.8, 'env1.release': 0.3,
      'lfo1.rate': 5.5, 'lfo1.shape': 'Sine',
    },
    fx: [{ type: 'Corroder', mix: 0.5, params: [220, 0.45, 0.4, 80, 7000, 0.25] }, { type: 'Delay', mix: 0.3, params: [375, 0.45, 5000, 0.8, '1/8D', 150] }, { type: 'Reverb', mix: 0.2, params: [0.6, 0.5, 10, 0.9, 200, 0] }],
    mods: [['macro1', 'fx1.mix', 0.5], ['macro2', 'fx1.p2', 0.6], ['macro3', 'a.wt.warp', 0.6], ['macro4', 'fx2.mix', 0.5], ['modwheel', 'a.fine', 0.0], ['lfo1', 'a.fine', 0.03], ['modwheel', 'lfo1.rate', 0.0]],
  },
  {
    name: 'Harmonic Organ', category: 'Keys', description: 'Síntesis aditiva con balance par/impar y peine espectral movido por LFO. Phaser y reverb.',
    macroNames: ['Partials', 'Odd/Even', 'Comb', 'Space'],
    params: {
      'a.type': 'Harmonic', 'a.harm.partials': 12, 'a.harm.tilt': 0.8, 'a.harm.oddEven': -0.3, 'a.harm.comb': 0.3, 'a.harm.detune': 0.15, 'a.level': 0.8,
      'b.on': 'On', 'b.type': 'Harmonic', 'b.harm.partials': 4, 'b.harm.tilt': 1.5, 'b.octave': -1, 'b.level': 0.5, 'b.filter': 'F1',
      'f1.cutoff': 10000, 'env1.attack': 0.01, 'env1.decay': 0.2, 'env1.sustain': 1, 'env1.release': 0.25,
      'lfo1.rate': 0.4, 'lfo1.shape': 'Triangle', 'lfo1.retrig': 'Free',
    },
    fx: [{ type: 'Phaser', mix: 0.45, params: [0.25, 0.6, 900, 0.5, '4', 0.6] }, { type: 'Reverb', mix: 0.3, params: [0.65, 0.4, 10, 1, 150, 0] }],
    mods: [['lfo1', 'a.harm.comb', 0.2], ['macro1', 'a.harm.partials', 0.6], ['macro2', 'a.harm.oddEven', 0.5], ['macro3', 'a.harm.comb', 0.5], ['macro4', 'fx2.mix', 0.5]],
  },
  {
    name: 'Arp Pluck', category: 'Sequence', description: 'Pulso analógico y tabla de armónicos con decaimiento corto; arpegiador arriba/abajo a 1/16 con delay ping‑pong.',
    macroNames: ['Cutoff', 'Decay', 'Echo', 'Width'],
    params: {
      'a.type': 'Analog', 'a.va.wave': 'Pulse', 'a.va.pw': 0.25, 'a.level': 0.7,
      'b.on': 'On', 'b.type': 'Wavetable', 'b.wt.table': 'Harmonics', 'b.wt.pos': 0.35, 'b.octave': 1, 'b.level': 0.4, 'b.filter': 'F1',
      'f1.type': 'LP24', 'f1.cutoff': 900, 'f1.res': 0.35, 'f1.keytrack': 0.5,
      'env1.attack': 0.001, 'env1.decay': 0.35, 'env1.sustain': 0, 'env1.release': 0.25,
      'env2.attack': 0.001, 'env2.decay': 0.2, 'env2.sustain': 0, 'env2.release': 0.2,
      'arp.on': 'On', 'arp.mode': 'Up/Down', 'arp.rate': '1/16', 'arp.octaves': 2, 'arp.gate': 0.4, 'master.tempo': 124,
    },
    fx: [{ type: 'Delay', mix: 0.35, params: [375, 0.5, 4000, 1, '1/8D', 200] }, { type: 'Reverb', mix: 0.25, params: [0.7, 0.4, 10, 1, 200, 0] }],
    mods: [['env2', 'f1.cutoff', 0.5], ['velocity', 'f1.cutoff', 0.2], ['macro1', 'f1.cutoff', 0.5], ['macro2', 'env1.decay', 0.4], ['macro3', 'fx1.mix', 0.5], ['macro4', 'b.wt.pos', 0.5]],
  },
  {
    name: 'Texture Drone', category: 'Texture', description: 'Granular sobre textura de ruido y loop de sample con filtro formante. Todo se mueve con LFOs lentos.',
    macroNames: ['Vowel', 'Density', 'Scan', 'Space'],
    params: {
      'a.type': 'Granular', 'a.gran.source': 'Texture', 'a.gran.size': 250, 'a.gran.density': 12, 'a.gran.pos': 0.5, 'a.gran.spray': 0.6, 'a.gran.pitchRnd': 7, 'a.gran.scan': 0.3, 'a.level': 0.7,
      'b.on': 'On', 'b.type': 'Sample', 'b.smp.source': 'Bell', 'b.smp.loop': 'On', 'b.smp.loopLen': 0.2, 'b.smp.start': 0.1, 'b.octave': -1, 'b.level': 0.4, 'b.filter': 'F2',
      'f1.type': 'Formant', 'f1.cutoff': 600, 'f1.res': 0.6, 'f2.type': 'Comb', 'f2.cutoff': 400, 'f2.res': 0.6,
      'env1.attack': 2, 'env1.decay': 1, 'env1.sustain': 1, 'env1.release': 4,
      'lfo1.rate': 0.04, 'lfo1.shape': 'Sine', 'lfo1.retrig': 'Free', 'lfo2.rate': 0.11, 'lfo2.shape': 'Drift', 'lfo2.retrig': 'Free', 'lfo3.rate': 0.02, 'lfo3.shape': 'Triangle',
    },
    fx: [{ type: 'Phaser', mix: 0.3, params: [0.08, 0.8, 600, 0.6, '8', 1] }, { type: 'Delay', mix: 0.3, params: [800, 0.6, 2500, 1, 'Free', 100] }, { type: 'Reverb', mix: 0.6, params: [0.95, 0.25, 60, 1, 100, 0.3] }],
    mods: [['lfo1', 'f1.cutoff', 0.3], ['macro1', 'f1.cutoff', 0.5], ['lfo2', 'a.gran.pos', 0.4], ['lfo3', 'f2.cutoff', 0.2], ['macro2', 'a.gran.density', 0.5], ['macro3', 'a.gran.scan', 0.4], ['macro4', 'fx3.mix', 0.4]],
  },
  {
    name: 'Sub Bass', category: 'Bass', description: 'Seno + sub cuadrado, mono legato con glide corto. Limpio y profundo.',
    macroNames: ['Sub', 'Tone', 'Glide', 'Comp'],
    params: {
      'a.type': 'Analog', 'a.va.wave': 'Sine', 'a.va.sub': 0.6, 'a.va.subWave': 'Square', 'a.level': 0.9, 'b.on': 'Off',
      'master.poly': 'Legato', 'master.glide': 0.06, 'f1.type': 'LP24', 'f1.cutoff': 400, 'f1.res': 0.1,
      'env1.attack': 0.005, 'env1.decay': 0.3, 'env1.sustain': 0.9, 'env1.release': 0.15,
    },
    fx: [{ type: 'Compressor', mix: 1, params: [-20, 4, 8, 120, 4, 0.5] }],
    mods: [['macro1', 'a.va.sub', 0.4], ['macro2', 'f1.cutoff', 0.5], ['macro3', 'master.glide', 0.3], ['macro4', 'fx1.p0', -0.3]],
  },
  {
    name: 'Modal Percussion', category: 'Percussion', description: 'Membrana modal excitada por ruido y arpegiador aleatorio. Macro 1 cambia el material.',
    macroNames: ['Material', 'Decay', 'Position', 'Space'],
    params: {
      'a.type': 'Modal', 'a.modal.material': 0.6, 'a.modal.modes': 16, 'a.modal.decay': 0.6, 'a.modal.damp': 0.7, 'a.modal.pos': 0.35, 'a.modal.exciter': 'Noise', 'a.modal.exLen': 6, 'a.modal.bright': 0.5, 'a.level': 0.9,
      'b.on': 'Off', 'f1.cutoff': 16000,
      'env1.attack': 0.001, 'env1.decay': 1, 'env1.sustain': 1, 'env1.release': 0.8,
      'arp.on': 'On', 'arp.mode': 'Random', 'arp.rate': '1/16', 'arp.octaves': 3, 'arp.gate': 0.2, 'arp.swing': 0.15, 'master.tempo': 110,
    },
    fx: [{ type: 'Delay', mix: 0.25, params: [250, 0.4, 5000, 1, '1/16', 200] }, { type: 'Reverb', mix: 0.35, params: [0.75, 0.4, 5, 1, 200, 0] }],
    mods: [['macro1', 'a.modal.material', 0.4], ['macro2', 'a.modal.decay', 0.4], ['macro3', 'a.modal.pos', 0.5], ['macro4', 'fx2.mix', 0.5], ['random', 'a.modal.pos', 0.3], ['velocity', 'a.modal.bright', 0.4]],
  },
  {
    name: 'Analog Brass', category: 'Lead', description: 'Dos sierras unison con envolvente de filtro rápida, chorus y EQ. Modwheel añade vibrato.',
    macroNames: ['Cutoff', 'Attack', 'Detune', 'Space'],
    params: {
      'a.type': 'Analog', 'a.va.wave': 'Saw', 'a.va.unison': 3, 'a.va.detune': 12, 'a.level': 0.75,
      'b.on': 'On', 'b.type': 'Analog', 'b.va.wave': 'Saw', 'b.va.unison': 3, 'b.va.detune': 18, 'b.semi': -12, 'b.level': 0.5, 'b.filter': 'F1',
      'f1.type': 'LP24', 'f1.cutoff': 700, 'f1.res': 0.2, 'f1.keytrack': 0.4,
      'env1.attack': 0.05, 'env1.decay': 0.4, 'env1.sustain': 0.8, 'env1.release': 0.3,
      'env2.attack': 0.08, 'env2.decay': 0.5, 'env2.sustain': 0.4, 'env2.release': 0.3,
      'lfo1.rate': 5, 'lfo1.shape': 'Sine',
    },
    fx: [{ type: 'Chorus', mix: 0.4, params: [0.7, 0.4, 10, 0.1, 0.7, '2'] }, { type: 'EQ', mix: 1, params: [2, 120, 1.5, 2500, 2, 8000] }, { type: 'Reverb', mix: 0.25, params: [0.6, 0.5, 10, 0.8, 200, 0] }],
    mods: [['env2', 'f1.cutoff', 0.55], ['velocity', 'f1.cutoff', 0.25], ['modwheel', 'a.fine', 0.0], ['lfo1', 'a.fine', 0.0], ['macro1', 'f1.cutoff', 0.4], ['macro2', 'env1.attack', 0.5], ['macro3', 'a.va.detune', 0.5], ['macro4', 'fx3.mix', 0.5]],
  },
  {
    name: 'FM Pluck', category: 'Pluck', description: 'FM en paralelo con feedback, Env 3 barre el índice. Delay sincronizado.',
    macroNames: ['Index', 'Feedback', 'Echo', 'Tone'],
    params: {
      'a.type': 'FM', 'a.fm.alg': '2+3›1', 'a.fm.ratio2': 2, 'a.fm.index2': 0.8, 'a.fm.ratio3': 7, 'a.fm.index3': 0.5, 'a.fm.feedback': 0.2, 'a.level': 0.8,
      'b.on': 'On', 'b.type': 'Analog', 'b.va.wave': 'Triangle', 'b.level': 0.3, 'b.octave': -1, 'b.filter': 'F1',
      'f1.cutoff': 9000, 'env1.attack': 0.001, 'env1.decay': 0.5, 'env1.sustain': 0.1, 'env1.release': 0.4,
      'env3.attack': 0.001, 'env3.decay': 0.25, 'env3.sustain': 0, 'env3.release': 0.2,
    },
    fx: [{ type: 'Delay', mix: 0.3, params: [375, 0.45, 4000, 0.9, '1/8D', 150] }, { type: 'Reverb', mix: 0.25, params: [0.6, 0.5, 10, 1, 200, 0] }],
    mods: [['env3', 'a.fm.index2', 0.3], ['env3', 'a.fm.index3', 0.2], ['velocity', 'a.fm.index2', 0.2], ['macro1', 'a.fm.index2', 0.4], ['macro2', 'a.fm.feedback', 0.5], ['macro3', 'fx1.mix', 0.5], ['macro4', 'f1.cutoff', -0.5]],
  },
];
